---
title: "Proyecto n1"
author: "Sebastian Herrera, Cristobal paredes"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=TRUE}
data <- read.csv(file.choose(), sep = ";", header= TRUE )
attach(data)
summary(data)
#install.packages("tidyverse")
library(tidyverse)
```
```{r eval=TRUE}
### Filtrar las mejores hamburguesas.

#se filtraran las mejores hamburguesas para asi ver de primera cuales son las que tienen mejores calificaciones
mejores_hamburguesas<- filter(data, nota >= 5)
```
```{r eval=TRUE}
### Separar los ingredientes de las mejores hamburguesas

# de esta manera se busca tener todos los ingredientes separados y poder ver cuales son los mejores, porque estos seran los mas utilizados por lo que tendran una mayor frecuencia de uso.
mejores_ingredientes<- strsplit(mejores_hamburguesas$Ingredientes, split=",") 
ingredientes_separados = data.frame(unlist(mejores_ingredientes))
```
```{r eval=TRUE}
### Diminucion de ruido

#capitalizar los ingredientes para no tener tanto ruido en los datos
library(tools)
texto_columnas <-unlist(lapply(ingredientes_separados, FUN=toTitleCase))
```
```{r eval=TRUE}
### Contando ingredientes

#Aqui se cuentan los ingredientes que mas se repiten para asi tener la frecuencia de estos
tabla <- table(texto_columnas)
tabla <- tibble(word = names(tabla), count = as.numeric(tabla))
tabla <- arrange(tabla, desc(count))
tabla
library(ggplot2)
gg = ggplot(data  = tabla, aes(x=word, y=count))
gg + geom_bar(stat = "identity")
#para la eleccion de la hamburguesa se utilizaran los primeros 9 ingredientes,pan de hamburguesa y hamburguesa ya que estas son por defecto las mas utilizadas en el mercado
hamburguesas<- filter(tabla, count>=3 )
hamburguesas
```